import * as fs from "node:fs";
import * as path from "node:path";

export const LOCK_FILENAME = "vulyk-lock.json";

const LEGACY_MARKER = ".vulyk";
const LEGACY_MARKER_PREFIX = "🍯 ";
const AGENT_FILENAMES = new Set(["AGENTS.md", "CLAUDE.md"]);

/**
 * The single source of truth for what vulyk has put on disk in this
 * project. Paths are root-relative (forward-slash separated), sorted
 * ascending. Files created by `vulyk sync` go into `syncPaths`; files
 * generated by `vulyk agents` go into `agentPaths`. Separate lists
 * prevent `vulyk sync` from deleting what `vulyk agents` produced
 * and vice versa.
 */
export interface LockState {
  version: 1;
  syncPaths: string[];
  agentPaths: string[];
}

export function emptyState(): LockState {
  return { version: 1, syncPaths: [], agentPaths: [] };
}

/**
 * Type guard: returns true iff `value` is an array whose every element
 * is a string. Used to safely parse unknown-shaped JSON.parse results
 * without resorting to `any` or layered unsafe casts.
 */
export function isStringArray(value: unknown): value is string[] {
  if (!Array.isArray(value)) return false;
  for (const item of value) {
    if (typeof item !== "string") return false;
  }
  return true;
}

/**
 * Narrow a JSON.parse result to a `LockState`. Returns null when the
 * parsed value is not an object, or has non-string-array syncPaths /
 * agentPaths. Tolerates extra fields by ignoring them.
 */
export function parseLockObject(value: unknown): LockState | null {
  if (!value || typeof value !== "object") return null;
  // We received `unknown` from JSON.parse; we need to read two well-known
  // keys before type predicates can narrow them. The assertion below is the
  // single boundary at which JSON lands into LockState; everything after is
  // narrowing through isStringArray.
  // eslint-disable-next-line @typescript-eslint/consistent-type-assertions -- the one JSON->LockState boundary; `satisfies` was rejected because `unknown` lacks the `syncPaths`/`agentPaths` keys
  const obj = value as { syncPaths?: unknown; agentPaths?: unknown };
  if (!isStringArray(obj.syncPaths)) return null;
  if (!isStringArray(obj.agentPaths)) return null;
  return {
    version: 1,
    syncPaths: obj.syncPaths,
    agentPaths: obj.agentPaths,
  };
}

function lockFilePath(dir: string): string {
  return path.join(dir, LOCK_FILENAME);
}

function toRootRelative(root: string, fullPath: string): string {
  const rel = path.relative(root, fullPath);
  return rel.split(path.sep).join("/");
}

/**
 * Read `vulyk-lock.json` from `dir`. If it is missing or unparseable,
 * perform the one-shot migration: scan for legacy .vulyk markers
 * in any subdirectory of the project,
 * split their contents into sync vs agent paths by filename heuristic,
 * delete the markers, and return the resulting state. If there are no
 * markers either, return an empty state.
 */
export function readState(dir: string): LockState {
  const lockPath = lockFilePath(dir);
  if (fs.existsSync(lockPath)) {
    try {
      const parsed: unknown = JSON.parse(fs.readFileSync(lockPath, "utf8"));
      const state = parseLockObject(parsed);
      if (state) return state;
    } catch {
      // Corrupt lockfile: fall through to migration. The next writeState
      // will replace it with a valid file.
    }
  }
  return migrateFromLegacyMarkers(dir);
}

/**
 * Atomically write the lockfile. Writes to `<dir>/vulyk-lock.json.tmp`
 * first and renames; readers either see the previous file or the
 * complete new file (no partial state).
 */
export function writeState(dir: string, state: LockState): void {
  const lockPath = lockFilePath(dir);
  const tmp = `${lockPath}.tmp`;
  // Last-write boundary defense: redundant with caller-side dedup today,
  // kept cheap so a single caller regression (e.g. agents files × N) can't
  // permanently pollute the lockfile.
  const payload = {
    version: 1,
    syncPaths: [...new Set(state.syncPaths)].sort(),
    agentPaths: [...new Set(state.agentPaths)].sort(),
  };
  fs.writeFileSync(tmp, `${JSON.stringify(payload, null, 2)}\n`, "utf8");
  fs.renameSync(tmp, lockPath);
}

const IGNORED_DIR_NAMES = new Set([
  ".git",
  "node_modules",
  ".next",
  ".turbo",
  ".yarn",
  "dist",
  "build",
  "coverage",
]);

/**
 * Delete paths in `prev` not in `curr`. After deleting a path, walk
 * up its parent chain and remove directories that have become empty
 * (stopping at but not deleting `dir`). Returns the resulting `curr`
 * list — callers typically pass it back as the next state.
 *
 * `prev` and `curr` are expected to be root-relative (forward-slash)
 * path strings.
 */
export function applyCleanupDelta(
  dir: string,
  prev: string[],
  curr: string[],
): void {
  const currSet = new Set(curr);
  for (const rel of prev) {
    if (currSet.has(rel)) continue;
    const abs = path.resolve(dir, rel);
    try {
      if (fs.existsSync(abs)) {
        fs.rmSync(abs, { recursive: true, force: true });
      }
    } catch {
      // best-effort
    }
    pruneEmptyParents(abs, dir);
  }
}

function pruneEmptyParents(abs: string, stopAt: string): void {
  let current = path.dirname(abs);
  while (
    current !== stopAt &&
    current !== path.dirname(current) &&
    (current.startsWith(stopAt + path.sep) || path.dirname(current) === stopAt)
  ) {
    let entries: string[];
    try {
      entries = fs.readdirSync(current);
    } catch {
      break;
    }
    if (entries.length > 0) break;
    try {
      fs.rmdirSync(current);
    } catch {
      break;
    }
    current = path.dirname(current);
  }
}

/**
 * Walk `dir` looking for legacy legacy .vulyk markers marker files. Categorise
 * each marker's contents:
 *   - `AGENTS.md` / `CLAUDE.md` lines -> `agentPaths`
 *   - any other file line           -> `syncPaths`
 *   - the bare legacy `🍯` marker   -> the containing dir -> `syncPaths`
 *
 * After enumeration, **delete the markers**. Returns the migrated
 * `LockState` (sorted). Caller writes it via `writeState` to seal the
 * transition; future `vulyk sync`/`agents` runs operate purely on
 * the lockfile.
 */
export function migrateFromLegacyMarkers(dir: string): LockState {
  const syncPaths = new Set<string>();
  const agentPaths = new Set<string>();
  const found: string[] = [];
  iterDir(dir, (entryPath, dirent) => {
    if (!dirent.isFile()) return;
    if (path.basename(entryPath) !== LEGACY_MARKER) return;
    found.push(entryPath);
  });
  for (const markerPath of found) {
    const markerDir = path.dirname(markerPath);
    let hasFileLine = false;
    try {
      const content = fs.readFileSync(markerPath, "utf8");
      for (const raw of content.split("\n")) {
        const trimmed = raw.trim();
        if (!trimmed) continue;
        if (trimmed === "🍯") continue; // legacy bare marker
        if (!trimmed.startsWith(LEGACY_MARKER_PREFIX)) continue;
        const name = trimmed.slice(LEGACY_MARKER_PREFIX.length).trim();
        if (!name) continue;
        hasFileLine = true;
        const rel = toRootRelative(dir, path.join(markerDir, name));
        if (AGENT_FILENAMES.has(name)) {
          agentPaths.add(rel);
        } else {
          syncPaths.add(rel);
        }
      }
      if (!hasFileLine) {
        syncPaths.add(toRootRelative(dir, markerDir));
      }
    } catch {
      // ignore unreadable markers
    }
  }
  for (const markerPath of found) {
    try {
      fs.rmSync(markerPath, { force: true });
    } catch {
      // best-effort
    }
  }
  return {
    version: 1,
    syncPaths: [...syncPaths].sort(),
    agentPaths: [...agentPaths].sort(),
  };
}

function iterDir(
  root: string,
  cb: (entryPath: string, dirent: fs.Dirent) => void,
): void {
  if (!fs.existsSync(root)) return;
  const stack: string[] = [root];
  while (stack.length > 0) {
    const cur = stack.pop();
    if (cur === undefined) break;
    let entries: fs.Dirent[];
    try {
      entries = fs.readdirSync(cur, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const e of entries) {
      const full = path.join(cur, e.name);
      cb(full, e);
      if (e.isDirectory() && !IGNORED_DIR_NAMES.has(e.name)) {
        stack.push(full);
      }
    }
  }
}
